import math
import pygame

RES = WIDTH, HEIGHT = 800, 450
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT// 2
HUD_HEIGHT = HEIGHT
FPS = 300

PLAYER_POS = 7, 5
PLAYER_ANGLE = 0
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 120

FLOOR_COLOR = (30, 30, 30)
FOG_COLOR = (0,0,10)

FOV = 1.1
HALF_FOV = FOV / 2
Q_SCALE = 4
NUM_RAYS = WIDTH // Q_SCALE
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 60

resize_buffer_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS
D_FLAGS = pygame.DOUBLEBUF | pygame.RESIZABLE

TRUE_TEXTURE_SIZE = 16
TEXTURE_SIZE = TRUE_TEXTURE_SIZE * Q_SCALE
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
